Customer Support Sample
dotnet/ai-samples pull request #74
Opened 2024-08-12 20:34 UTC by luisquintanilla

2024-08-13 18:39 UTC, luisquintanilla commented
@jmatthiesen this is ready for review when you get a chance. Thanks.

2024-08-13 19:45 UTC, luisquintanilla commented on .devcontainer.json
> +    "containerEnv": {
Remove these.

2024-08-13 19:45 UTC, luisquintanilla commented on src/samples/CustomerSupport/README.md
> +
```suggestion
Add project description.
```

2024-08-13 20:37 UTC, jmatthiesen commented
This is looking great, thanks for sharing, Luis!

Per a conversation we just had IRL, here are some suggestion
* Update the Readme to provide an overview of the scenario being demonstrated with this sample.
* We want to establish a pattern for folder structure to demonstrate different use cases in this repo. For a folder name, what do you think of `src/data-ingestion/` or `src/data-ingestion-localdotnet`? Other suggestions welcome

2024-08-13 23:03 UTC, luisquintanilla commented on .devcontainer.json
> +    "containerEnv": {
Done

2024-08-13 23:03 UTC, luisquintanilla commented on src/samples/CustomerSupport/README.md
> +
Done

2024-08-13 23:07 UTC, luisquintanilla commented
I think since this one is more generally concerned with chat, we can use chat for this one.

So the path can be `src/chat`. We can play around with it after the fact.

2024-08-17 22:53 UTC, jmatthiesen requested changes

2024-08-17 22:53 UTC, jmatthiesen commented on .devcontainer.json
> +{
I'm also getting this error when using Codespaces:

`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
2024-08-17 22:51:40.087Z: Stop: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount type=volume,src=dind-var-lib-docker-0hcbhh2c7vldoj773drm1bjldnb89u0rt96sl9nju22d9ou8d14n,dst=/var/lib/docker --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e CODESPACES=******** -e ContainerVersion=13 -e RepositoryName=ai-samples --gpus all --label ContainerVersion=13 --hostname codespaces-82c536 --add-host codespaces-82c536:127.0.0.1 --cap-add sys_nice --network host --privileged --entrypoint /bin/sh vsc-ai-samples-ac7d8fa2041ac73b151cb3eae118357442b9086c698dd3a2853cd6402e799649-features -c echo Container started
2024-08-17 22:51:40.119Z: Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount type=volume,src=dind-var-lib-docker-0hcbhh2c7vldoj773drm1bjldnb89u0rt96sl9nju22d9ou8d14n,dst=/var/lib/docker --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=ai-samples --gpus all --label ContainerVersion=13 --hostname codespaces-82c536 --add-host codespaces-82c536:127.0.0.1 --cap-add sys_nice --network host --privileged --entrypoint /bin/sh vsc-ai-samples-ac7d8fa2041ac73b151cb3eae118357442b9086c698dd3a2853cd6402e799649-features -c echo Container started
2024-08-17 22:51:40.120Z: trap "exit 0" 15
2024-08-17 22:51:40.120Z: {"outcome":"error","message":"Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount type=volume,src=dind-var-lib-docker-0hcbhh2c7vldoj773drm1bjldnb89u0rt96sl9nju22d9ou8d14n,dst=/var/lib/docker --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=ai-samples --gpus all --label ContainerVersion=13 --hostname codespaces-82c536 --add-host codespaces-82c536:127.0.0.1 --cap-add sys_nice --network host --privileged --entrypoint /bin/sh vsc-ai-samples-ac7d8fa2041ac73b151cb3eae118357442b9086c698dd3a2853cd6402e799649-features -c echo Container started\ntrap \"exit 0\" 15\n/usr/local/share/docker-init.sh\nexec \"$@\"\nwhile sleep 1 & wait $!; do :; done -","description":"An error occurred setting up the container.","containerId":"467320ac6b3e85493a22fbd26e043012f0dca8e6b1217c64f693a0524e817e6f"}
`

2024-08-19 15:57 UTC, luisquintanilla commented on src/chat/CustomerSupport/OllamaChatCompletionService.cs
> +public class OllamaChatCompletionService : IChatCompletionService
The intent of this is mainly aesthetic for now. It's a simplified implementation of the Ollama feature branch in SK. 

In the future, we'd replace this with the SK implementation.

2024-08-19 16:02 UTC, luisquintanilla commented on src/chat/CustomerSupport/Program.cs
> +var openAIKey = Environment.GetEnvironmentVariable("AZURE_AI_KEY");
Do you have a sample that shows how to do that?

2024-08-19 16:03 UTC, luisquintanilla commented on .devcontainer.json
> +{
I'll create separate versions (CPU and GPU)

2024-08-19 16:50 UTC, luisquintanilla commented on .devcontainer.json
> +{
Done

2024-08-19 19:57 UTC, luisquintanilla commented on src/chat/CustomerSupport/Program.cs
> +var openAIKey = Environment.GetEnvironmentVariable("AZURE_AI_KEY");
Pushed managed identity in latest update.

2024-08-19 19:58 UTC, luisquintanilla commented
@jmatthiesen this is ready for review / merge with the changes you suggested.

2024-08-19 23:42 UTC, jmatthiesen approved these changes

2024-08-20 00:04 UTC, luisquintanilla commented
Thanks for the review @jmatthiesen.

Can you please merge when you get a chance. I don't have write access. Thanks!

2024-08-20 01:08 UTC, merged